import "./globals.css";
import SideBar from "./SideBar";

export const metadata = {
  title: "Pomodoro App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col md:flex-row w-screen  h-screen">
          <SideBar />
          {children}
        </div>
      </body>
    </html>
  );
}
