import "./globals.css";
import NavBar from "./NavBar.tsx";
import Task from "./Task";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col md:flex-row w-screen  h-screen bg-gray-200">
          <NavBar />
          {children}
          <Task />
        </div>
      </body>
    </html>
  );
}
